services:
  sqlserver:
    build:
      context: .
      dockerfile: Dockerfile  # Usando o Dockerfile para criar a imagem personalizada
    user: root
    ports:
      - 1433:1433
    restart: always